// Curated hairstyle presets for the AI hairstyle changer: 10 styles with 5
// choices each. Each preset is a prompt fragment applied to the user's
// photo — no reference image needed. `cover` is an Unsplash photo id used on
// marketing surfaces. Keep ids stable: home page cards link to ?style=<id>.

export const hairCategories = [
  "Short cuts",
  "Men's styles",
  "Bobs",
  "Bangs & fringe",
  "Layers & shag",
  "Long & sleek",
  "Waves & curls",
  "Braids & locs",
  "Natural & afro",
  "Bold color",
] as const;

export type HairCategory = (typeof hairCategories)[number];

export type HairPreset = {
  id: string;
  name: string;
  category: HairCategory;
  prompt: string;
  tint: string;
  cover?: string;
};

export const hairPresets: HairPreset[] = [
  {
    id: "pixie-cut",
    name: "Pixie cut",
    category: "Short cuts",
    prompt: "a cropped pixie cut with soft side-swept bangs",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "buzz-cut",
    name: "Buzz cut",
    category: "Short cuts",
    prompt: "a clean, even buzz cut",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "crew-cut",
    name: "Crew cut",
    category: "Short cuts",
    prompt: "a neat, short crew cut, slightly longer on top",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "french-crop",
    name: "French crop",
    category: "Short cuts",
    prompt: "a textured French crop with a short blunt fringe and faded sides",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "classic-fade",
    name: "Classic fade",
    category: "Short cuts",
    prompt: "a classic short taper fade, neatly combed on top",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "slick-back",
    name: "Slicked-back undercut",
    category: "Men's styles",
    prompt: "a slicked-back top with a clean undercut on the sides",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "silver-quiff",
    name: "Silver quiff",
    category: "Men's styles",
    prompt: "a short textured quiff with faded sides in silver-grey",
    tint: "var(--pop-pink-bold)",
    cover: "1660144689256-c9a4a4ac116c",
  },
  {
    id: "side-part",
    name: "Side part",
    category: "Men's styles",
    prompt: "a classic gentleman's side part with a neat taper",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "modern-mullet",
    name: "Modern mullet",
    category: "Men's styles",
    prompt:
      "a modern textured mullet, shorter on the sides and longer at the back",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "man-bun",
    name: "Man bun",
    category: "Men's styles",
    prompt: "shoulder-length hair pulled back into a neat top knot bun",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "copper-bob",
    name: "Copper bob",
    category: "Bobs",
    prompt: "a chin-length copper bob with soft, polished ends",
    tint: "var(--pop-orange-bold)",
    cover: "1438761681033-6461ffad8d80",
  },
  {
    id: "blunt-bob",
    name: "Blunt bob",
    category: "Bobs",
    prompt: "a sharp, jaw-length blunt bob with a straight hemline",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "long-bob",
    name: "Long bob",
    category: "Bobs",
    prompt: "a collarbone-length lob with soft, piecey ends",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "french-bob",
    name: "French bob",
    category: "Bobs",
    prompt: "a short French bob at cheekbone length with a light fringe",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "asymmetric-bob",
    name: "Asymmetric bob",
    category: "Bobs",
    prompt: "an asymmetric bob, longer on one side with a sleek finish",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "curtain-bangs",
    name: "Curtain bangs",
    category: "Bangs & fringe",
    prompt: "shoulder-length hair with soft curtain bangs",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "wispy-bangs",
    name: "Wispy bangs",
    category: "Bangs & fringe",
    prompt: "long hair with light, wispy see-through bangs",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "blunt-bangs",
    name: "Blunt bangs",
    category: "Bangs & fringe",
    prompt: "straight hair with full, blunt eyebrow-length bangs",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "side-swept-bangs",
    name: "Side-swept bangs",
    category: "Bangs & fringe",
    prompt: "layered hair with long side-swept bangs",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "middle-part",
    name: "Middle-part curtains",
    category: "Bangs & fringe",
    prompt:
      "medium-length hair parted in the middle, falling as soft curtains around the face",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "wolf-cut",
    name: "Wolf cut",
    category: "Layers & shag",
    prompt: "a choppy, textured wolf cut with feathered layers",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "shag",
    name: "Classic shag",
    category: "Layers & shag",
    prompt: "a 70s-style shag with choppy layers and a feathered fringe",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "butterfly-cut",
    name: "Butterfly cut",
    category: "Layers & shag",
    prompt: "a voluminous butterfly cut with short face-framing layers",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "long-layers",
    name: "Long layers",
    category: "Layers & shag",
    prompt: "long, glossy hair with face-framing layers",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "curly-shag",
    name: "Curly shag",
    category: "Layers & shag",
    prompt: "a curly shag cut with bouncy layers and curly bangs",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "sleek-straight",
    name: "Sleek straight",
    category: "Long & sleek",
    prompt: "long, sleek, straight hair with a center part",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "bouncy-blowout",
    name: "Bouncy blowout",
    category: "Long & sleek",
    prompt: "a voluminous, bouncy blowout with rounded layers",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "half-up",
    name: "Half-up, half-down",
    category: "Long & sleek",
    prompt: "long hair styled half-up, half-down with loose waves",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "high-ponytail",
    name: "High ponytail",
    category: "Long & sleek",
    prompt: "long hair in a sleek, high ponytail",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "low-bun",
    name: "Sleek low bun",
    category: "Long & sleek",
    prompt: "hair pulled back into a polished, sleek low bun",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "beach-waves",
    name: "Beach waves",
    category: "Waves & curls",
    prompt: "long, loose beach waves with sun-kissed highlights",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "long-curls",
    name: "Long curls",
    category: "Waves & curls",
    prompt: "long, voluminous, defined dark curls",
    tint: "var(--pop-pink-bold)",
    cover: "1569430548104-6ca1cda3ec41",
  },
  {
    id: "hollywood-waves",
    name: "Hollywood waves",
    category: "Waves & curls",
    prompt: "glamorous, glossy vintage Hollywood waves",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "spiral-curls",
    name: "Spiral curls",
    category: "Waves & curls",
    prompt: "bouncy, defined spiral curls at shoulder length",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "loose-curls",
    name: "Loose curls",
    category: "Waves & curls",
    prompt: "soft, loose curls with lots of volume",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "box-braids",
    name: "Box braids",
    category: "Braids & locs",
    prompt: "long, neat box braids",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "cornrows",
    name: "Cornrows",
    category: "Braids & locs",
    prompt: "neat straight-back cornrow braids",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "locs",
    name: "Locs",
    category: "Braids & locs",
    prompt: "shoulder-length, well-groomed locs",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "dutch-braids",
    name: "Dutch braids",
    category: "Braids & locs",
    prompt: "two tight Dutch braids running from the hairline to the ends",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "twists",
    name: "Senegalese twists",
    category: "Braids & locs",
    prompt: "long, sleek Senegalese twists",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "afro",
    name: "Natural afro",
    category: "Natural & afro",
    prompt: "a full, rounded natural afro",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "twist-out",
    name: "Twist-out",
    category: "Natural & afro",
    prompt: "a defined, voluminous twist-out on natural hair",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "tapered-afro",
    name: "Tapered afro",
    category: "Natural & afro",
    prompt: "a short tapered afro, fuller on top and shorter at the sides",
    tint: "var(--pop-mint-bold)",
  },
  {
    id: "afro-puff",
    name: "Afro puff",
    category: "Natural & afro",
    prompt: "natural hair gathered into a high afro puff",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "bantu-knots",
    name: "Bantu knots",
    category: "Natural & afro",
    prompt: "neat bantu knots across the head",
    tint: "var(--pop-yellow-bold)",
  },
  {
    id: "platinum-blonde",
    name: "Platinum blonde",
    category: "Bold color",
    prompt: "the same haircut recolored platinum blonde",
    tint: "var(--pop-orange-bold)",
  },
  {
    id: "cherry-red",
    name: "Cherry red",
    category: "Bold color",
    prompt: "the same haircut recolored a vivid cherry red",
    tint: "var(--pop-pink-bold)",
  },
  {
    id: "pastel-shag",
    name: "Pastel shag",
    category: "Bold color",
    prompt: "a layered shag cut with pastel blue and lilac tones",
    tint: "var(--pop-mint-bold)",
    cover: "1648213037568-2c9c6d267e25",
  },
  {
    id: "honey-balayage",
    name: "Honey balayage",
    category: "Bold color",
    prompt: "the same haircut with a soft honey-blonde balayage",
    tint: "var(--pop-sky-bold)",
  },
  {
    id: "rose-pink",
    name: "Rose pink",
    category: "Bold color",
    prompt: "the same haircut recolored a soft rose pink",
    tint: "var(--pop-yellow-bold)",
  },
];

export function getHairPreset(id: string): HairPreset | undefined {
  return hairPresets.find((preset) => preset.id === id);
}
